name: Generate Documentation
on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install JSDoc
      run: npm install -g jsdoc

    - name: Generate Docs
      run: |
        mkdir -p ./docs/api
        jsdoc index.js -d ./docs/api
        echo "<!DOCTYPE html>
        <html>
        <head>
          <title>ClubSiteCMS Docs</title>
          <meta http-equiv='refresh' content='0; url=./api/index.html'>
        </head>
        <body>
          Redirecting to documentation...
        </body>
        </html>" > ./docs/index.html

    - name: Verify
      run: |
        ls -R ./docs
