name: Debug Documentation Build

on:
  push:
    branches:
      - main # Eller den grenen du jobber på
  workflow_dispatch: # Tillater manuell kjøring

permissions:
  contents: write # Nødvendig for å pushe til gh-pages

jobs:
  debug-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Eller den versjonen du foretrekker

      - name: Install JSDoc
        run: npm install -g jsdoc

      - name: Generate Docs with Verbose Logging
        run: |
          mkdir -p ./docs/api
          # Sørg for at index.js finnes, ellers vil jsdoc feile
          # For testing, hvis index.js ikke er klar: touch index.js
          if [ ! -f index.js ]; then echo "Creating dummy index.js for JSDoc" > index.js; fi
          jsdoc index.js -d ./docs/api --verbose 2>&1 | tee jsdoc.log
          echo "Generated files:"
          find ./docs -type f
          cat jsdoc.log

      # Viktig nytt steg:
      - name: Create .nojekyll file
        run: touch ./docs/.nojekyll

      - name: Force Push to gh-pages
        run: |
          git config --global user.name 'actions-user'
          git config --global user.email 'actions-user@github.com'
          git add docs
          git commit -m "Force update docs" --allow-empty
          git push -f origin HEAD:gh-pages

      - name: Generate JSDoc
        run: npx jsdoc -c jsdoc.json

