name: Debug Documentation Build
on: [push]

jobs:
  debug-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Debug Node.js Setup
      run: |
        echo "Node.js version: $(node -v)"
        echo "npm version: $(npm -v)"
        ls -la

    - name: Install JSDoc with Debug
      run: |
        npm install -g jsdoc
        echo "JSDoc version: $(jsdoc --version)"

    - name: Generate Docs with Verbose Logging
      run: |
        mkdir -p ./docs/api
        jsdoc index.js -d ./docs/api --verbose 2>&1 | tee jsdoc.log
        echo "Generated files:"
        find ./docs -type f
        cat jsdoc.log

    - name: Force Push to gh-pages
      if: always()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./docs
        git commit -m "Force update docs" || echo "No changes to commit"
        git push origin HEAD:gh-pages --force
