name: Generate Documentation  
on: [push]  

jobs:  
  docs:  
    runs-on: ubuntu-latest  
    steps:  
    - uses: actions/checkout@v4  
    - name: Setup Node  
      uses: actions/setup-node@v4  
      with:  
        node-version: '20'  
    - name: Install JSDoc  
      run: npm install -g jsdoc  
    - name: Generate Docs  
      run: |
            jsdoc index.js -d ./docs cp ./docs/index.html ./docs/api/index.html  
    - name: List Generated Files  
      run: ls -R ./docs  # Verifiser at filer er opprettet  
